import java.io.*;
import java.util.*;

public class ParseTableBuilder {
    private Grammar grammar;
    private FirstFollow ff;
    private LinkedHashMap<String, LinkedHashMap<String, String>> table;
    private ArrayList<String> conflicts;

    static final String OUTPUT_PATH = "/home/jarvis2026/Documents/Repos/compiler construction/Compiler Construction java/tests/ParseTable.txt";
    public ParseTableBuilder(Grammar grammar, FirstFollow ff) {
        this.grammar   = grammar;
        this.ff        = ff;
        this.table     = new LinkedHashMap<>();
        this.conflicts = new ArrayList<>();

        for (String nt : grammar.getProductions().keySet()) {
            table.put(nt, new LinkedHashMap<>());
        }
    }

    public void build() {
        for (String nt : grammar.getProductions().keySet()) {
            for (List<String> production : grammar.getProductions().get(nt)) {
                LinkedHashSet<String> firstOfProd = ff.firstOfString(production);
                String prodStr = String.join(" ", production);
                for (String terminal : firstOfProd) {
                    if (!terminal.equals("epsilon")) {
                        addEntry(nt, terminal, prodStr);
                    }
                }
                if (firstOfProd.contains("epsilon")) {
                    for (String terminal : ff.getFollow(nt)) {
                        addEntry(nt, terminal, prodStr);
                    }
                }
            }
        }
    }

    private void addEntry(String nt, String terminal, String production) {
        LinkedHashMap<String, String> row = table.get(nt);
        if (row.containsKey(terminal)) {
            String existing = row.get(terminal);
            if (!existing.equals(production)) {
                conflicts.add("CONFLICT at M[" + nt + ", " + terminal + "]: \""
                    + existing + "\" vs \"" + production + "\"");
            }
        }
        else {
            row.put(terminal, production);
        }
    }

    public void writeToFile() throws IOException {
        writeToFile(OUTPUT_PATH);
    }

    public void writeToFile(String path) throws IOException {
        PrintWriter pw = new PrintWriter(new FileWriter(path));
        pw.println("# LL(1) PARSING TABLE");
        pw.println("# Format: NonTerminal,Terminal=Production");
        pw.println("# Epsilon is represented as epsilon");
        pw.println("# Empty entries are omitted (treated as ERROR)");
        pw.println("# Auto-generated by ParseTableBuilder.java");
        pw.println();
        pw.println("TABLE_BEGIN");
        for (String nt : grammar.getProductions().keySet()) {
            for (Map.Entry<String, String> entry : table.get(nt).entrySet()) {
                pw.println(nt + "," + entry.getKey() + "=" + entry.getValue());
            }
        }
        pw.println("TABLE_END");
        pw.println();
        pw.println("TERMINALS_BEGIN");

        for (String t : ff.getTerminals()) pw.println(t);
        pw.println("$");
        pw.println("TERMINALS_END");
        pw.println();

        pw.println("NONTERMINALS_BEGIN");
        for (String nt : grammar.getProductions().keySet()) pw.println(nt);
        pw.println("NONTERMINALS_END");
        pw.println();

        pw.println("FOLLOW_BEGIN");
        for (String nt : grammar.getProductions().keySet()) {
            LinkedHashSet<String> followSet = ff.getFollow(nt);
            if (!followSet.isEmpty()) {
                pw.println(nt + "=" + String.join(" ", followSet));
            }
        }
        pw.println("FOLLOW_END");

        pw.close();
        System.out.println("[OK] ParseTable.txt written to: " + path);
    }

    public void print() {
        Set<String> cols = new LinkedHashSet<>(ff.getTerminals());
        cols.add("$");

        System.out.println("===== LL(1) PARSING TABLE =====");
        System.out.printf("  %-15s", "");
        for (String t : cols) System.out.printf("| %-22s", t);
        System.out.println("|");
        System.out.println("  " + "-".repeat(15 + cols.size() * 23));

        for (String nt : grammar.getProductions().keySet()) {
            System.out.printf("  %-15s", nt);
            for (String t : cols) {
                String entry = table.get(nt).getOrDefault(t, "");
                if (entry.length() > 20) entry = entry.substring(0, 17) + "...";
                System.out.printf("| %-22s", entry);
            }
            System.out.println("|");
        }
        System.out.println();

        if (conflicts.isEmpty()) {
            System.out.println("Grammar IS LL(1) -- no conflicts.");
        }
        else {
            System.out.println("Grammar is NOT LL(1) -- conflicts:");
            for (String c : conflicts) System.out.println("  " + c);
        }
        System.out.println("================================\n");
    }

    public boolean isLL1() { return conflicts.isEmpty(); }
    public ArrayList<String> getConflicts() { return conflicts; }
}
