/* The following code was generated by JFlex 1.7.0 */

/* ========================================================================
   Scanner.flex - JFlex Specification for Compiler Scanner
   CS4031 - Compiler Construction Assignment 01
   ======================================================================== */

/* ========================================================================
   USER CODE SECTION
   ======================================================================== */
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\5\1\62\1\62\1\4\22\0\1\4\1\40\1\32"+
    "\1\35\1\0\1\47\1\43\1\34\1\51\1\52\1\36\1\45\1\57"+
    "\1\27\1\30\1\46\12\1\1\61\1\60\1\41\1\37\1\42\2\0"+
    "\4\2\1\31\25\2\1\55\1\33\1\56\1\50\1\3\1\0\1\10"+
    "\1\25\1\21\1\22\1\23\1\12\1\3\1\15\1\13\1\3\1\26"+
    "\1\16\1\3\1\14\1\17\1\20\1\3\1\11\1\6\1\7\1\24"+
    "\5\3\1\53\1\44\1\54\7\0\1\62\u1fa2\0\1\62\1\62\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\13\1\1\5\1\6"+
    "\3\1\1\7\1\10\1\11\1\12\1\13\2\1\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\0\1\3\15\0\1\31"+
    "\1\32\1\0\1\33\3\0\1\34\1\0\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\3\15\0\1\51\1\0\1\50\1\0"+
    "\1\3\1\0\1\52\5\0\1\53\4\0\1\54\1\0"+
    "\1\55\2\50\1\0\1\3\1\56\1\0\1\57\2\0"+
    "\1\60\4\0\1\61\1\50\1\3\1\62\1\63\1\0"+
    "\1\64\3\0\1\50\1\3\3\0\1\65\1\50\1\3"+
    "\1\66\1\67\1\0\1\3\1\70\26\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd"+
    "\0\u0330\0\63\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462"+
    "\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9"+
    "\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\63\0\63\0\u0363\0\63\0\u08c4\0\u08f7\0\u092a\0\u095d"+
    "\0\u0990\0\63\0\63\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\u09c3\0\u09f6\0\u0a29\0\u0a5c"+
    "\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4"+
    "\0\u0c27\0\u0c5a\0\u0c8d\0\63\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59"+
    "\0\u0d8c\0\63\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\63"+
    "\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\63\0\u0f8a\0\63\0\u0fbd"+
    "\0\u0ff0\0\u0ff0\0\u1023\0\63\0\u1056\0\63\0\u1089\0\u10bc"+
    "\0\63\0\u10ef\0\u1122\0\u1155\0\u1188\0\63\0\u11bb\0\u11ee"+
    "\0\63\0\63\0\u1221\0\63\0\u1254\0\u1287\0\u12ba\0\u12ed"+
    "\0\u1320\0\u1353\0\u1386\0\u13b9\0\63\0\u13ec\0\u141f\0\63"+
    "\0\63\0\u1452\0\u1485\0\63\0\u14b8\0\u14eb\0\u151e\0\u1551"+
    "\0\u1584\0\u15b7\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6\0\u16e9"+
    "\0\u171c\0\u174f\0\u1782\0\u17b5\0\u17e8\0\u181b\0\u184e\0\u1881"+
    "\0\u18b4\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\2\5\1\6\1\7\1\2"+
    "\1\10\1\11\1\12\2\2\1\13\1\14\1\2\1\15"+
    "\1\16\1\17\1\2\1\20\1\2\1\21\1\22\1\4"+
    "\1\23\1\2\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\65\0\1\3\26\0\1\52\33\0\3\53\2\0\21\53"+
    "\2\0\1\53\35\0\2\5\64\0\1\54\64\0\1\55"+
    "\74\0\1\56\47\0\1\57\2\0\1\60\10\0\1\61"+
    "\52\0\1\62\65\0\1\63\67\0\1\64\55\0\1\65"+
    "\66\0\1\66\55\0\1\67\55\0\1\70\52\0\1\3"+
    "\25\0\1\71\7\0\1\72\23\0\5\73\1\0\24\73"+
    "\1\74\1\75\27\73\5\76\1\0\25\76\1\77\1\0"+
    "\26\76\35\0\1\100\1\101\62\0\1\102\1\103\62\0"+
    "\1\104\62\0\1\105\62\0\1\106\62\0\1\107\66\0"+
    "\1\110\63\0\1\111\17\0\1\3\35\0\1\112\5\0"+
    "\1\113\54\0\1\114\24\0\1\115\62\0\3\116\2\0"+
    "\21\116\2\0\1\116\41\0\1\117\76\0\1\120\45\0"+
    "\1\121\71\0\1\122\60\0\1\123\62\0\1\124\66\0"+
    "\1\125\61\0\1\126\52\0\1\127\67\0\1\130\67\0"+
    "\1\131\47\0\1\132\77\0\1\133\46\0\1\73\1\0"+
    "\1\73\2\0\1\73\15\0\2\73\63\0\1\134\35\0"+
    "\1\76\1\0\1\76\2\0\1\76\16\0\2\76\26\0"+
    "\5\100\1\0\55\100\36\101\1\135\24\101\1\0\1\136"+
    "\21\0\1\137\5\0\1\137\32\0\3\140\2\0\21\140"+
    "\2\0\1\140\42\0\1\141\74\0\1\142\63\0\1\143"+
    "\44\0\1\144\67\0\1\145\70\0\1\146\65\0\1\147"+
    "\56\0\1\150\62\0\1\151\51\0\1\152\12\0\1\153"+
    "\56\0\1\154\67\0\1\155\47\0\1\156\52\0\35\101"+
    "\1\157\1\135\24\101\1\0\1\160\21\0\1\137\5\0"+
    "\1\137\32\0\1\161\25\0\1\162\15\0\1\162\16\0"+
    "\3\163\2\0\21\163\2\0\1\163\40\0\1\164\64\0"+
    "\1\165\74\0\1\166\45\0\1\167\63\0\1\170\62\0"+
    "\1\171\77\0\1\172\51\0\1\173\62\0\1\174\57\0"+
    "\1\175\100\0\1\176\35\0\1\177\21\0\1\137\5\0"+
    "\1\137\32\0\1\161\62\0\3\200\2\0\21\200\2\0"+
    "\1\200\45\0\1\201\63\0\1\202\60\0\1\203\56\0"+
    "\1\204\67\0\1\205\55\0\1\206\64\0\1\207\52\0"+
    "\1\210\21\0\1\137\5\0\1\137\32\0\3\211\2\0"+
    "\21\211\2\0\1\211\50\0\1\212\67\0\1\213\51\0"+
    "\1\214\72\0\1\215\40\0\1\216\21\0\1\137\5\0"+
    "\1\137\32\0\3\217\2\0\21\217\2\0\1\217\45\0"+
    "\1\220\71\0\1\221\56\0\1\222\66\0\1\137\5\0"+
    "\1\137\32\0\3\223\2\0\21\223\2\0\1\223\45\0"+
    "\1\224\47\0\3\225\2\0\21\225\2\0\1\225\32\0"+
    "\3\226\2\0\21\226\2\0\1\226\32\0\3\227\2\0"+
    "\21\227\2\0\1\227\32\0\3\230\2\0\21\230\2\0"+
    "\1\230\32\0\3\231\2\0\21\231\2\0\1\231\32\0"+
    "\3\232\2\0\21\232\2\0\1\232\32\0\3\233\2\0"+
    "\21\233\2\0\1\233\32\0\3\234\2\0\21\234\2\0"+
    "\1\234\32\0\3\235\2\0\21\235\2\0\1\235\32\0"+
    "\3\236\2\0\21\236\2\0\1\236\32\0\3\237\2\0"+
    "\21\237\2\0\1\237\32\0\3\240\2\0\21\240\2\0"+
    "\1\240\32\0\3\241\2\0\21\241\2\0\1\241\32\0"+
    "\3\242\2\0\21\242\2\0\1\242\32\0\3\243\2\0"+
    "\21\243\2\0\1\243\32\0\3\244\2\0\21\244\2\0"+
    "\1\244\32\0\3\245\2\0\21\245\2\0\1\245\32\0"+
    "\3\246\2\0\21\246\2\0\1\246\32\0\3\247\2\0"+
    "\21\247\2\0\1\247\32\0\3\250\2\0\21\250\2\0"+
    "\1\250\32\0\3\251\2\0\21\251\2\0\1\251\32\0"+
    "\3\252\2\0\21\252\2\0\1\252\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6375];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\17\1\1\11\14\1\13\11\1\0\1\1"+
    "\15\0\2\11\1\0\1\11\3\0\1\1\1\0\13\11"+
    "\2\1\15\0\1\11\1\0\1\1\1\0\1\1\1\0"+
    "\1\11\5\0\1\11\4\0\1\11\1\0\1\11\2\1"+
    "\1\0\1\1\1\11\1\0\1\11\2\0\1\11\4\0"+
    "\1\11\2\1\2\11\1\0\1\11\3\0\2\1\3\0"+
    "\1\11\2\1\2\11\1\0\1\1\1\11\25\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /* Helper method to create tokens */
    private Token token(String type) {
        return new Token(type, yytext(), yyline + 1, yycolumn + 1);
    }
    
    private Token token(String type, Object value) {
        return new Token(type, yytext(), value, yyline + 1, yycolumn + 1);
    }
    
    /* Helper method to create error tokens */
    private Token error(String message) {
        return Token.error(message, yytext(), yyline + 1, yycolumn + 1);
    }

    /* Token class to represent lexical tokens */
    public static class Token {
        public String type;
        public String lexeme;
        public Object value;
        public int line;
        public int column;
        public boolean isError;
        public String errorMessage;

        public Token(String type, String lexeme, int line, int column) {
            this.type = type;
            this.lexeme = lexeme;
            this.value = lexeme;
            this.line = line;
            this.column = column;
            this.isError = false;
        }

        public Token(String type, String lexeme, Object value, int line, int column) {
            this.type = type;
            this.lexeme = lexeme;
            this.value = value;
            this.line = line;
            this.column = column;
            this.isError = false;
        }

        // Static factory method for error tokens
        public static Token error(String errorMessage, String lexeme, int line, int column) {
            Token token = new Token("ERROR", lexeme, line, column);
            token.isError = true;
            token.errorMessage = errorMessage;
            return token;
        }

        @Override
        public String toString() {
            if (isError) {
                return String.format("ERROR: %s [%s] | Line: %d | Column: %d",
                                   errorMessage, lexeme, line, column);
            }
            return String.format("<%s, '%s', Line: %d, Col: %d>",
                               type, lexeme, line, column);
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return error("Illegal character");
            } 
            // fall through
          case 57: break;
          case 2: 
            { return token("TOK_INTEGER", Integer.parseInt(yytext()));
            } 
            // fall through
          case 58: break;
          case 3: 
            { return token("TOK_IDENTIFIER");
            } 
            // fall through
          case 59: break;
          case 4: 
            { /* Skip whitespace, line/column tracking is automatic */
            } 
            // fall through
          case 60: break;
          case 5: 
            { return token("TOK_MINUS");
            } 
            // fall through
          case 61: break;
          case 6: 
            { return token("TOK_DOT");
            } 
            // fall through
          case 62: break;
          case 7: 
            { return token("TOK_STAR");
            } 
            // fall through
          case 63: break;
          case 8: 
            { return token("TOK_EQ");
            } 
            // fall through
          case 64: break;
          case 9: 
            { return token("TOK_NOT");
            } 
            // fall through
          case 65: break;
          case 10: 
            { return token("TOK_LT");
            } 
            // fall through
          case 66: break;
          case 11: 
            { return token("TOK_GT");
            } 
            // fall through
          case 67: break;
          case 12: 
            { return token("TOK_PLUS");
            } 
            // fall through
          case 68: break;
          case 13: 
            { return token("TOK_DIV");
            } 
            // fall through
          case 69: break;
          case 14: 
            { return token("TOK_MOD");
            } 
            // fall through
          case 70: break;
          case 15: 
            { return token("TOK_LOGICALXOR");
            } 
            // fall through
          case 71: break;
          case 16: 
            { return token("TOK_LPAREN");
            } 
            // fall through
          case 72: break;
          case 17: 
            { return token("TOK_RPAREN");
            } 
            // fall through
          case 73: break;
          case 18: 
            { return token("TOK_LCURLY");
            } 
            // fall through
          case 74: break;
          case 19: 
            { return token("TOK_RCURLY");
            } 
            // fall through
          case 75: break;
          case 20: 
            { return token("TOK_LSQUAR");
            } 
            // fall through
          case 76: break;
          case 21: 
            { return token("TOK_RSQUAR");
            } 
            // fall through
          case 77: break;
          case 22: 
            { return token("TOK_COMMA");
            } 
            // fall through
          case 78: break;
          case 23: 
            { return token("TOK_SEMICOLON");
            } 
            // fall through
          case 79: break;
          case 24: 
            { return token("TOK_COLON");
            } 
            // fall through
          case 80: break;
          case 25: 
            { return token("TOK_DEC");
            } 
            // fall through
          case 81: break;
          case 26: 
            { return token("TOK_MINUSASSIGN");
            } 
            // fall through
          case 82: break;
          case 27: 
            { return token("TOK_STRING", yytext().substring(1, yytext().length()-1));
            } 
            // fall through
          case 83: break;
          case 28: 
            { /* Skip single-line comments */
            } 
            // fall through
          case 84: break;
          case 29: 
            { return token("TOK_EXPONENT");
            } 
            // fall through
          case 85: break;
          case 30: 
            { return token("TOK_MULASSIGN");
            } 
            // fall through
          case 86: break;
          case 31: 
            { return token("TOK_EQEQ");
            } 
            // fall through
          case 87: break;
          case 32: 
            { return token("TOK_NE");
            } 
            // fall through
          case 88: break;
          case 33: 
            { return token("TOK_LE");
            } 
            // fall through
          case 89: break;
          case 34: 
            { return token("TOK_GE");
            } 
            // fall through
          case 90: break;
          case 35: 
            { return token("TOK_LOGICALAND");
            } 
            // fall through
          case 91: break;
          case 36: 
            { return token("TOK_LOGICALOR");
            } 
            // fall through
          case 92: break;
          case 37: 
            { return token("TOK_PLUSASSIGN");
            } 
            // fall through
          case 93: break;
          case 38: 
            { return token("TOK_INC");
            } 
            // fall through
          case 94: break;
          case 39: 
            { return token("TOK_DIVASSIGN");
            } 
            // fall through
          case 95: break;
          case 40: 
            { return token("TOK_FLOAT", Double.parseDouble(yytext()));
            } 
            // fall through
          case 96: break;
          case 41: 
            { return token("TOK_CHAR", yytext().charAt(1));
            } 
            // fall through
          case 97: break;
          case 42: 
            { return token("TOK_TRUE");
            } 
            // fall through
          case 98: break;
          case 43: 
            { return token("TOK_LOOP");
            } 
            // fall through
          case 99: break;
          case 44: 
            { return token("TOK_ELSE");
            } 
            // fall through
          case 100: break;
          case 45: 
            { /* Skip multi-line comments */
            } 
            // fall through
          case 101: break;
          case 46: 
            { return token("TOK_START");
            } 
            // fall through
          case 102: break;
          case 47: 
            { return token("TOK_FALSE");
            } 
            // fall through
          case 103: break;
          case 48: 
            { return token("TOK_INPUT");
            } 
            // fall through
          case 104: break;
          case 49: 
            { return token("TOK_BREAK");
            } 
            // fall through
          case 105: break;
          case 50: 
            { return token("TOK_RETURN");
            } 
            // fall through
          case 106: break;
          case 51: 
            { return token("TOK_FINISH");
            } 
            // fall through
          case 107: break;
          case 52: 
            { return token("TOK_OUTPUT");
            } 
            // fall through
          case 108: break;
          case 53: 
            { return token("TOK_DECLARE");
            } 
            // fall through
          case 109: break;
          case 54: 
            { return token("TOK_FUNCTION");
            } 
            // fall through
          case 110: break;
          case 55: 
            { return token("TOK_CONTINUE");
            } 
            // fall through
          case 111: break;
          case 56: 
            { return token("TOK_CONDITION");
            } 
            // fall through
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
